# ln -s path/to/dotfiles/helix-config.toml ~/.config/helix/config.toml
theme = "papercolor-dark"

[editor]
line-number = "relative"
color-modes = true
auto-save = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = {k = "normal_mode"}

